export const spirits = [
  {
    id: "1",
    name: "Tanuki",
    threatLevel: { value: "Low", color: "#4CAF50" },
    location: "Roppongi",
    status: "Active",
    image: "/images/spirits/tanuki.jpg",
  },
  {
    id: "2",
    name: "Kitsune",
    threatLevel: { value: "Medium", color: "#FFC107" },
    location: "Shibuya",
    status: "Active",
    image: "/images/spirits/kitsune.jpg",
  },
  {
    id: "3",
    name: "Mujina",
    threatLevel: { value: "Critical", color: "#D32F2F" },
    location: "Akihabara",
    status: "Active",
    image: "/images/spirits/mujina.jpg",
  },
  {
    id: "4",
    name: "Tengu",
    threatLevel: { value: "High", color: "#FF5722" },
    location: "Shinjuku",
    status: "Active",
    image: "/images/spirits/tengu.jpg",
  },
  {
    id: "5",
    name: "Inugami",
    threatLevel: { value: "Low", color: "#4CAF50" },
    location: "Asakusa",
    status: "Captured",
    image: "/images/spirits/inugami.jpg",
  },
  {
    id: "6",
    name: "Kappa",
    threatLevel: { value: "Medium", color: "#FFC107" },
    location: "Setagaya",
    status: "Active",
    image: "/images/spirits/kappa.jpg",
  },
  {
    id: "7",
    name: "Bakeneko",
    threatLevel: { value: "High", color: "#FF5722" },
    location: "Meguro",
    status: "Active",
    image: "/images/spirits/bakeneko.jpg",
  },
  {
    id: "8",
    name: "Okami",
    threatLevel: { value: "Critical", color: "#D32F2F" },
    location: "Harajuku",
    status: "Active",
    image: "/images/spirits/okami.jpg",
  },
];
